config/routes.rb
Qed::Application.routes.draw do

  resources :projects do
    resources :posts, :controller => "project_posts"
  end

  resources :posts

  match 'projects/:project_id/languages' => 'projects#assign_languages', :via => :put
  match 'projects/:project_id/frameworks' => 'projects#assign_frameworks', :via => :put
  match 'projects/:project_id/vcs' => 'projects#assign_vcs', :via => :put
  match 'projects/:project_id/ci' => 'projects#assign_ci', :via => :put
  match 'projects/:project_id/build-tools' => 'projects#assign_build_tools', :via => :put
  match 'projects/:project_id/infrastucture-management-tools' => 'projects#assign_infrastructure_management_tools', :via => :put
  match 'projects/:project_id/operating-system' => 'projects#assign_operating_system', :via => :put
  match 'projects/:project_id/off-the-shelf-products' => 'projects#assign_off_the_shelf_products', :via => :put
  match 'projects/:project_id/cloud-usage' => 'projects#assign_cloud_usage', :via => :put
  match 'projects/:project_id/databases' => 'projects#assign_databases', :via => :put

   root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @all_projects = Project.find_all
  end
end

app/views/home/index.html.erb
<div class="span6">
  <ul class="thumbnails">
    <% @all_projects.each do |project| %>
      <li class="span3">
        <div class="thumbnail">
          <div class="caption">
          <h3><%= project.name%></h3>
          <p>
            Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula.
          </p>
          <p>
            <%= link_to "View", project_path(project.id), :class => "btn btn-primary" %>
          </p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>