config/routes.rb
Qed::Application.routes.draw do

  resources :projects do
    resources :posts, :controller => "project_posts"
  end

  resources :posts

  match 'projects/:project_id/languages' => 'projects#assign_languages', :via => :put
  match 'projects/:project_id/frameworks' => 'projects#assign_frameworks', :via => :put
  match 'projects/:project_id/vcs' => 'projects#assign_vcs', :via => :put
  match 'projects/:project_id/ci' => 'projects#assign_ci', :via => :put
  match 'projects/:project_id/build-tools' => 'projects#assign_build_tools', :via => :put
  match 'projects/:project_id/infrastucture-management-tools' => 'projects#assign_infrastructure_management_tools', :via => :put
  match 'projects/:project_id/operating-system' => 'projects#assign_operating_system', :via => :put
  match 'projects/:project_id/off-the-shelf-products' => 'projects#assign_off_the_shelf_products', :via => :put
  match 'projects/:project_id/cloud-usage' => 'projects#assign_cloud_usage', :via => :put
  match 'projects/:project_id/databases' => 'projects#assign_databases', :via => :put

   root :to => 'home#index'

end

app/models/project.rb
class Project
	attr_reader :id, :name, :languages, :frameworks, :vcs, :build_tools,
							:ci, :infrastructure_tools, :operating_system, 
							:off_the_shelf_products, :cloud_usage,:databases,:posts

	def initialize(params)
		@id = params["id"]
		@name = params["name"]
	end

	def self.create(name)
		id = SecureRandom.uuid
		project_name = name.strip
    $redis.hmset "projects:#{id}","id","#{id}","name","#{project_name}"
		$redis.sadd "projects","#{id}"
		Project.new({"id" => id, "name" => project_name})
	end

	def self.find_by_id(id)
		project = nil;
		if $redis.exists "projects:#{id}"
			name = $redis.hget "projects:#{id}","name"
			project = Project.new({"id" => id, "name" => name})
		end
		project
	end

	def self.find_all
		all_projects_id = $redis.smembers "projects"
		all_projects_id.map do |id|
			Project.find_by_id id
		end 
	end

	def add_post(post)
		posts #populate @posts if not done
		added = $redis.sadd "projects:#{@id}:posts", post.id
		@posts.push post if added
	end


	# Will do some fancy meta-programming to remove all this nonsense
	def rget(attribute)
		$redis.smembers "projects:#{@id}:"+attribute
	end

	def languages
		if(@languages.nil?)
			@languages = rget "languages"
		end
		@languages
	end

	def frameworks
		if(@frameworks.nil?)
			@frameworks = rget "frameworks"
		end
		@frameworks
	end

	def vcs
		if(@vcd.nil?)
			@vcs = rget "vcs"
		end
		@vcs
	end

	def ci
		if(@ci.nil?)
			@ci = rget "ci"
		end
		@ci
	end

	def build_tools
		if(@build_tools.nil?)
			@build_tools = rget "build-tools"
		end
		@build_tools
	end

	def infrastructure_tools
		if(@infrastructure_tools.nil?)
			@infrastructure_tools = rget "infrastructure-tools"
		end
		@infrastructure_tools
	end

	def operating_system
		if(@operating_system.nil?)
			@operating_system = rget "operating-system"
		end
		@operating_system
	end

	def off_the_shelf_products
		if(@off_the_shelf_products.nil?)
			@off_the_shelf_products = rget "products"
		end
		@off_the_shelf_products
	end

	def cloud_usage
		if(@cloud_usage.nil?)
			@cloud_usage = rget "cloud-usage"
		end
		@cloud_usage
	end

	def databases
		if(@databases.nil?)
			@databases = rget "db"
		end
		@databases
	end

	def posts
		if(@posts.nil?)
			all_post_ids = rget "posts"
			@posts = all_post_ids.map {|id| Post.find_by_id id}
		end
		@posts
	end

	def rset(attribute,value)
		key = "projects:#{@id}:"+attribute
		$redis.del key
		if(!value.empty?)
			$redis.sadd key,value.map {|tag| tag.strip.downcase}
		end
		$redis.smembers key
	end

	def assign_languages(languages)
		@languages = rset "languages",languages
	end

	def assign_frameworks(frameworks)
		@frameworks = rset "frameworks",frameworks
	end

	def assign_vcs(vcs)
		@vcs = rset "vcs",vcs
	end

	def assign_build_tools(build_tools)
		@build_tools = rset "build-tools",build_tools
	end

	def assign_ci(ci)
		@ci = rset "ci",ci
	end

	def assign_infrastructure_management_tools(infrastructure)
		@infrastructure = rset "infrastructure-tools",infrastructure
	end

	def assign_operating_system(operating_system)
	  @operating_system = rset "operating-system", operating_system
	end

	def assign_off_the_shelf_products(products)
	  @off_the_shelf_products = rset "products",products
	end

	def assign_cloud_usage(cloud_usage)
	  @cloud_usage = rset "cloud-usage",cloud_usage
	end

	def assign_databases(databases)
	  @databases = rset "db",databases
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
 
 def new
 	@project_name = params[:project_name]
 end

 def create
 	project_name = params[:project_name]
 	@project = Project.create project_name
	flash[:success] = "Created project #{project_name}"
 	redirect_to :action => :show, :id => @project.id
 end

 def show
 	id = params[:id]
  @project = Project.find_by_id id
  if @project == nil 
    not_found
  end
 end

 def assign_languages
   project = Project.find_by_id params[:project_id]
   project.assign_languages params[:data].split(",")
   render :nothing => true
 end

 def assign_frameworks
   project = Project.find_by_id params[:project_id]
   project.assign_frameworks params[:data].split(",")
   render :nothing => true
 end

 def assign_vcs
   project = Project.find_by_id params[:project_id]
   project.assign_vcs params[:data].split(",")
   render :nothing => true
 end

 def assign_ci
   project = Project.find_by_id params[:project_id]
   project.assign_ci params[:data].split(",")
   render :nothing => true
 end

 def assign_infrastructure_management_tools
   project = Project.find_by_id params[:project_id]
   project.assign_infrastructure_management_tools params[:data].split(",")
   render :nothing => true
 end

 def assign_build_tools
   project = Project.find_by_id params[:project_id]
   project.assign_build_tools params[:data].split(",")
   render :nothing => true
 end

 def assign_operating_system
   project = Project.find_by_id params[:project_id]
   project.assign_operating_system params[:data].split(",")
   render :nothing => true
 end

 def assign_off_the_shelf_products
   project = Project.find_by_id params[:project_id]
   project.assign_off_the_shelf_products params[:data].split(",")
   render :nothing => true
 end

 def assign_cloud_usage
   project = Project.find_by_id params[:project_id]
   project.assign_cloud_usage params[:data].split(",")
   render :nothing => true
 end

 def assign_databases
   project = Project.find_by_id params[:project_id]
   project.assign_databases params[:data].split(",")
   render :nothing => true
 end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  def tag_input project,item_name,title,value
    raw "<div id='#{item_name}' class='span4'>
      <h5>
        #{title}
        <button id='#{item_name}-edit-icon' title='edit' class='edit-icon btn btn-primary btn-mini' >edit</button>
        <button id='#{item_name}-done-icon' title='done' class='done-icon btn btn-success btn-mini hide' href='/projects/#{project.id}/#{item_name}'>save</button>
      </h5>
      <div id='#{item_name}-tags-container' class='clearfix'></div>
      <input id='input-#{item_name}' type='text' name='#{item_name}-tags' value='#{value}' class='#{item_name}-tag-manager tagManager'/>
    </div>"
  end
end

app/views/projects/_technical.html.erb
<div class="row tag-row">
  <%= tag_input(@project,"languages","Languages",@project.languages.join(",")) %>
  <%= tag_input(@project,"frameworks","Framework",@project.frameworks.join(",")) %>
  <%= tag_input(@project,"vcs","Version Control System",@project.vcs.join(",")) %>
</div>
<div class="row tag-row">
  <%= tag_input(@project,"build-tools","Build Tools",@project.build_tools.join(",")) %>
  <%= tag_input(@project,"ci","CI",@project.ci.join(",")) %>
  <%= tag_input(@project,"infrastucture-management-tools","Infrastructure Management",@project.infrastructure_tools.join(",")) %>
</div>
<div class="row tag-row">
  <%= tag_input(@project,"databases","Data Stores",@project.databases.join(",")) %>
  <%= tag_input(@project,"off-the-shelf-products","Off-The-Shelf Products",@project.off_the_shelf_products.join(",")) %>
  <%= tag_input(@project,"cloud-usage","Cloud Usage",@project.cloud_usage.join(",")) %>
</div>
<div class="row tag-row">
  <%= tag_input(@project,"operating-system","Operating Systems",@project.operating_system.join(",")) %>
</div>

app/views/projects/new.html.erb
<% if flash[:error] %>
	<div class="alert alert-error">
		<%= flash[:error] %>
	</div>
<% end %>
<%= form_tag("/projects", :class => "form-horizontal") do %>
	<legend>Create project</legend>
	<div class="control-group">
		<%= label_tag(:project_name, "Project name:", :class => "control-label") %>
		<%= text_field_tag(:project_name, @project_name , :class => "controls") %>
	</div>
	<%= submit_tag("create",:class =>"btn btn-primary") %>
<% end %>

app/views/projects/show.html.erb
<% if flash[:success] %>
	<div class="alert alert-success">
		<%= flash[:success] %>
	</div>
<% end %>

<div class="page-header">
  <h3><%= @project.name %></h3>
</div>

<h4>
  About
  <button id="about-edit-icon" title="edit" class="about-edit-icon btn btn-primary btn-mini">edit</button>
</h4>
<p id="about" class="well">
  Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula.

  Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ullamcorper nulla non metus auctor fringilla. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Donec ullamcorper nulla non metus auctor fringilla.
</p>

<ul class="nav nav-tabs" id="project-nav">
  <li class="active"><a href="#technical">Technical</a></li>
  <li><a href="#analysis">Analysis</a></li>
  <li><a href="#testing">Testing</a></li>
  <li><a href="#project-management">Project Management</a></li>
  <li><a href="#team">Team</a></li>
</ul>
 
<div id="project-details" class="tab-content">
  <div class="tab-pane active" id="technical">
    <%= render "technical" %>
  </div>
  <div class="tab-pane" id="analysis">...</div>
  <div class="tab-pane" id="testing">...</div>
  <div class="tab-pane" id="project-management">...</div>
  <div class="tab-pane" id="team">...</div>
</div>

<div class="row">
  <div class="span12">
  <div class="page-header sub-heading">
    <h4>Content
      <%= link_to "Add New Post", new_project_post_url(@project.id), :class =>  "btn btn-primary btn-mini"%>
    </h4>
  </div>
  <ul class="thumbnails">
    <% @project.posts.each do |post| %>
      <li class="span3">
        <div class="thumbnail">
          <div class="caption">
          <h5><%= post.title%></h5>
          <p>
            <%= link_to "View", post_path(post.id), :class => "btn btn-primary btn-mini" %>
          </p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    new Qed.ShowProject().init();
  })
</script>