config/routes.rb
Qed::Application.routes.draw do

  resources :projects do
    resources :posts, :controller => "project_posts"
  end

  resources :posts

  match 'projects/:project_id/languages' => 'projects#assign_languages', :via => :put
  match 'projects/:project_id/frameworks' => 'projects#assign_frameworks', :via => :put
  match 'projects/:project_id/vcs' => 'projects#assign_vcs', :via => :put
  match 'projects/:project_id/ci' => 'projects#assign_ci', :via => :put
  match 'projects/:project_id/build-tools' => 'projects#assign_build_tools', :via => :put
  match 'projects/:project_id/infrastucture-management-tools' => 'projects#assign_infrastructure_management_tools', :via => :put
  match 'projects/:project_id/operating-system' => 'projects#assign_operating_system', :via => :put
  match 'projects/:project_id/off-the-shelf-products' => 'projects#assign_off_the_shelf_products', :via => :put
  match 'projects/:project_id/cloud-usage' => 'projects#assign_cloud_usage', :via => :put
  match 'projects/:project_id/databases' => 'projects#assign_databases', :via => :put

   root :to => 'home#index'

end

app/models/post.rb
class Post
  attr_reader :id,:text,:title,:tags,:project_id

  def initialize params
    @id = params[:id]
    @title = params[:title]
    @text = params[:text]
    @tags = params[:tags]
    @project_id = params[:project_id]
  end

  def self.create(title,text,tags,project_id)
    id = SecureRandom.uuid
    $redis.hmset "posts:#{id}","id","#{id}","title","#{title}","text","#{text}",:project_id,"#{project_id}"
    $redis.sadd "posts:#{id}:tags",tags.map {|t| t.strip.downcase} unless tags.empty?
    Post.new({:id => id,:text => text,:tags => tags,:title => title, :project_id => project_id})
  end

  def self.find_by_id(id)
    post = nil
    if $redis.exists "posts:#{id}"
      id,text,title,project_id = $redis.hmget "posts:#{id}","id","text","title","project_id"
      tags = $redis.smembers "posts:#{id}:tags"
      post = Post.new({:id=> id, :text=>text, :tags => tags, :title => title, :project_id => project_id})
    end
    post
  end

  def update(title,text,tags)
    $redis.hmset "posts:#{@id}","title","#{title}","text","#{text}"
    $redis.del "posts:#{@id}:tags"
    $redis.sadd "posts:#{@id}:tags",tags.map {|t| t.strip.downcase} unless tags.empty?
    @title = title
    @text = text
    @tags = tags
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    id = params[:id]
    @post = Post.find_by_id id
  end

  def edit
    id = params[:id]
    @post = Post.find_by_id id
  end

  def update
    id = params[:id]
    @post = Post.find_by_id id
    @post.update params[:title],params[:post_text],params[:post_tags].split(",")
    redirect_to :action=>"show", :id => @post.id
  end

end

app/views/posts/edit.html.erb
 <div class="page-header">
  <h3>Edit post</h3>
</div>
 <%= form_tag(post_path(@post.id), {:method => :put}) do %>
  <div class="control-group">
    <%= label_tag(:title, "Title:", :class => "control-label") %>
    <%= text_field_tag(:title, @post.title , :class => "controls input-xxlarge") %>

     <div class="wmd-panel">
      <div id="wmd-button-bar"></div>
        <textarea class="wmd-input span12" name="post_text" id="wmd-input"><%= @post.text%></textarea>
      </div>


      <%= label_tag(:title, "Tags:", :class => "tag-manager control-label") %>
      <div id='tag-container' class='clearfix'></div>
      <%= text_field_tag(:tag, @post.tags.join(",") , :class => "controls",:id => "post-tags-input") %>
  </div>
   
  <%= submit_tag("update",:class =>"btn btn-primary") %>
 <% end %>


<div class="row">
  <div class="span12">
    <div class="page-header sub-heading">
      <h5>Preview</h5>
    </div>
    <div id="wmd-preview" class="wmd-panel wmd-preview"></div>   
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function(){
    new Qed.NewPost().init();
  })
</script>

app/views/posts/show.html.erb
<div class="page-header">
  <h3><%= @post.title%>
    <%= link_to "Edit", edit_post_url(@post.id), :class =>  "btn btn-primary btn-mini pull-right"%>
  </h3>
</div>

<div id="content"></div>
<input type="hidden" id="post-text" value="<%= @post.text%>"></input>

<hr/>

<h4>Tags</h4>
<div id='tags-container' class='clearfix'></div>
<input id="post-tags" name="tags" value="<%= @post.tags.join(',')%>"></input>

<script type="text/javascript">
  $(document).ready(function(){
    new Qed.ShowPost().init();
  })
</script>